#!/usr/bin/env python3
"""
Normalise the head, images and outbound links of the hand-written pages.

Hand-written guides (and /about/, /contact/) had incomplete social tags, images
with no dimensions, and affiliate links that were not marked as sponsored even
though the editorial policy says they are. This script fixes those without
touching the author's prose, and is idempotent.

  * Open Graph + Twitter tags, complete and consistent with <title>, the meta
    description and the canonical URL (between SOCIAL markers)
  * <img>: width/height that match the delivered crop, srcset/sizes, lazy loading
    and async decoding (Cloudinary and Unsplash delivery URLs are transformed so
    a phone never downloads a desktop original)
  * affiliate booking links -> rel="noopener sponsored"; any target="_blank" ->
    rel contains noopener
  * every <table> is wrapped in a labelled, keyboard-focusable scroll region so a
    wide table scrolls inside itself instead of stretching the whole page on a phone
  * Article JSON-LD gains dateModified (newest change-log entry), image and
    mainEntityOfPage — only values the data supports

    python3 tools/apply-seo.py [--check]
"""
import json
import os
import re
import sys
from html import unescape

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nt import render, store  # noqa: E402
from nt.paths import ROOT, SITE  # noqa: E402

CLD = "https://res.cloudinary.com/duhuxaukd/image/upload"
BEGIN, END = "<!-- BEGIN:SOCIAL (generated by tools/apply-seo.py) -->", "<!-- END:SOCIAL -->"
AFFILIATE = re.compile(r"(makemytrip|goibibo|oyo(rooms)?|redbus|yatra|cleartrip|booking\.com|agoda|abhibus|tripadvisor)\.", re.I)
SKIP = {"nav-template.html", "404.html"}


def og_image_for(slug, posts):
    p = posts.get(slug)
    if p and "/upload/" in p.get("image", ""):
        head, tail = p["image"].split("/upload/", 1)
        if not re.match(r"^[a-z]_", tail):
            return "%s/upload/f_auto,q_auto,c_fill,g_auto,w_1200,h_630/%s" % (head, tail)
        return p["image"]
    return None


def social_block(title, desc, url, image, alt, kind):
    return """%s
  <meta property="og:title" content="%s" />
  <meta property="og:description" content="%s" />
  <meta property="og:url" content="%s" />
  <meta property="og:type" content="%s" />
  <meta property="og:site_name" content="NashikTourism.com" />
  <meta property="og:locale" content="en_IN" />
  <meta property="og:image" content="%s" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="%s" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="%s" />
  <meta name="twitter:description" content="%s" />
  <meta name="twitter:image" content="%s" />
  %s""" % (BEGIN, title, desc, url, kind, image, alt, title, desc, image, END)


def fix_head(html, path, posts):
    t = re.search(r"<title>(.*?)</title>", html, re.S)
    d = re.search(r'<meta name="description" content="([^"]*)"', html)
    c = re.search(r'<link rel="canonical" href="([^"]*)"', html)
    if not (t and d and c):
        return html
    slug = path.strip("/").split("/")[-1]
    image = og_image_for(slug, posts) or "https://res.cloudinary.com/duhuxaukd/image/upload/f_auto,q_auto,c_fill,g_auto,w_1200,h_630/v1775450543/rishu-bhosale-LO0KOsgTEA0-unsplash_hqa4n3.jpg"
    alt = "Nashik, Maharashtra" if slug not in posts else render.esc(re.sub(r"\s*\|.*$", "", unescape(t.group(1))).strip())
    kind = "article" if path.startswith("/blog/") and path != "/blog/" else "website"
    # drop every existing og:/twitter: tag and the previous block, then insert one complete block
    html = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?\s*", "", html, flags=re.S)
    html = re.sub(r'[ \t]*<meta (?:property="og:[^"]*"|name="twitter:[^"]*")[^>]*>\n?', "", html)
    block = social_block(t.group(1).strip(), d.group(1), c.group(1), image, alt, kind)
    html = re.sub(r'(<link rel="canonical"[^>]*>)', lambda m: m.group(1) + "\n  " + block, html, count=1)
    return html


def img_attrs(tag):
    return dict(re.findall(r'([\w:-]+)="([^"]*)"', tag))


def fix_img(tag):
    a = img_attrs(tag)
    src = a.get("src", "")
    if src.startswith("/") or ("width" in a and "height" in a and "srcset" in a):
        return tag
    new = dict(a)
    if "res.cloudinary.com" in src and "/upload/" in src:
        head, tail = src.split("/upload/", 1)
        if re.match(r"^[a-z]_", tail):
            return tag if ("width" in a and "height" in a) else tag.replace("<img", '<img width="800" height="533"', 1)
        mk = lambda w: "%s/upload/f_auto,q_auto,c_fill,g_auto,ar_3:2,w_%d/%s" % (head, w, tail)  # noqa: E731
    elif "images.unsplash.com" in src:
        base = src.split("?")[0]
        mk = lambda w: "%s?w=%d&q=75&auto=format&fit=crop&ar=3:2" % (base, w)  # noqa: E731
    else:
        return tag
    new["src"] = mk(800)
    new["srcset"] = "%s 400w, %s 800w, %s 1200w" % (mk(400), mk(800), mk(1200))
    new.setdefault("sizes", "(max-width: 640px) 92vw, (max-width: 1100px) 48vw, 560px")
    new["width"], new["height"] = "800", "533"
    new.setdefault("loading", "lazy")
    new.setdefault("decoding", "async")
    order = ["class", "src", "srcset", "sizes", "width", "height", "alt", "loading", "decoding"]
    keys = [k for k in order if k in new] + [k for k in new if k not in order]
    return "<img " + " ".join('%s="%s"' % (k, new[k]) for k in keys) + " />"




def fix_tables(body):
    """Wrap each bare <table> in a scroll region labelled by its caption or nearest heading."""
    out, last = [], 0
    for m in re.finditer(r"<table\b.*?</table>", body, re.S):
        before = body[:m.start()]
        if re.search(r'<div class="table-scroll"[^>]*>\s*$', before):
            continue
        cap = re.search(r"<caption[^>]*>(.*?)</caption>", m.group(0), re.S)
        heads = re.findall(r"<h[23][^>]*>(.*?)</h[23]>", before, re.S)
        label = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", (cap.group(1) if cap else (heads[-1] if heads else "Data table")))).strip() or "Data table"
        label = unescape(label)[:90]
        out.append(body[last:m.start()])
        out.append('<div class="table-scroll" tabindex="0" role="region" aria-label="%s">%s</div>' % (render.esc("Table: " + label), m.group(0)))
        last = m.end()
    out.append(body[last:])
    return "".join(out)


def fix_links(html):
    def a_tag(m):
        tag = m.group(0)
        href = re.search(r'href="([^"]*)"', tag)
        if not href:
            return tag
        rel = re.search(r'rel="([^"]*)"', tag)
        rels = set(rel.group(1).split()) if rel else set()
        want = set(rels)
        if AFFILIATE.search(href.group(1)):
            want |= {"noopener", "sponsored"}
        if 'target="_blank"' in tag:
            want |= {"noopener"}
        if want == rels:
            return tag
        val = " ".join(sorted(want))
        return tag.replace(rel.group(0), 'rel="%s"' % val) if rel else tag.replace("<a ", '<a rel="%s" ' % val, 1)
    return re.sub(r"<a\s[^>]*>", a_tag, html)


def fix_jsonld(html, path, modified, posts):
    def repl(m):
        try:
            data = json.loads(m.group(1))
        except ValueError:
            return m.group(0)
        if isinstance(data, dict) and data.get("@type") == "Article":
            slug = path.strip("/").split("/")[-1]
            if modified:
                data["dateModified"] = modified
            data["mainEntityOfPage"] = {"@type": "WebPage", "@id": SITE + path}
            img = og_image_for(slug, posts)
            if img:
                data["image"] = img
            return '<script type="application/ld+json">%s</script>' % json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
        return m.group(0)
    return re.sub(r'<script type="application/ld\+json">(.*?)</script>', repl, html, flags=re.S)


def process(html, path, posts, modified):
    html = fix_head(html, path, posts)
    i, j = html.find("<main"), html.rfind("</main>")
    if i > 0 and j > i:
        body = re.sub(r"<img\s[^>]*>", lambda m: fix_img(m.group(0)), html[i:j])
        body = fix_tables(body)
        html = html[:i] + body + html[j:]
    html = fix_links(html)
    html = fix_jsonld(html, path, modified, posts)
    return html


def main():
    check = "--check" in sys.argv
    posts = {p["slug"]: p for p in json.load(open(os.path.join(ROOT, "posts.json"), encoding="utf-8"))}
    newest = {}
    for e in store.load("changelog")["entries"]:
        p = e["path"].split("#")[0]
        newest[p] = max(newest.get(p, ""), e["date"])
    changed = 0
    for dirpath, _d, files in os.walk(ROOT):
        for n in files:
            if not n.endswith(".html") or n in SKIP:
                continue
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
            path = "/" if rel == "index.html" else "/" + rel[:-len("index.html")]
            # Only hand-written pages: guides, about, contact. Generated pages already have a complete head.
            if not (path.startswith("/blog/") and path != "/blog/" or path in ("/about/", "/contact/", "/disclaimer/")):
                continue
            before = open(full, encoding="utf-8").read()
            mod = newest.get(path) or (posts.get(path.strip("/").split("/")[-1], {}) or {}).get("date")
            after = process(before, path, posts, mod)
            if after != before:
                changed += 1
                if not check:
                    with open(full, "w", encoding="utf-8") as fh:
                        fh.write(after)
    print("%s %d page(s)" % ("would update" if check else "updated", changed))


if __name__ == "__main__":
    main()
