#!/usr/bin/env python3
"""
Inject the "how current is this guide?" notice and the verification block into the
hand-written guides, from data — so a status change is one edit, not twenty-two.

For each guide listed in data/pages.json this writes two blocks, between markers,
so the script is idempotent and never touches the author's prose:

    <!-- BEGIN:NT-STATUS -->  right after <article class="article-body">
    <!-- BEGIN:NT-VERIFY -->  just before </article>

NT-STATUS says, in plain words, how far the guide can be relied on (the wording
depends on the guide's `notice` type) and, for Kumbh-related guides, repeats the
canonical dates straight from data/facts.json with their status — so when a date
is verified or changes in the fact database, every guide shows it on the next
build. NT-VERIFY shows publication date, verification status, sources to check
and the page's change history.

    python3 tools/apply-verification.py [--check]
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nt import render, store  # noqa: E402
from nt.paths import ROOT  # noqa: E402

S_BEGIN, S_END = "<!-- BEGIN:NT-STATUS (generated by tools/apply-verification.py — do not edit) -->", "<!-- END:NT-STATUS -->"
V_BEGIN, V_END = "<!-- BEGIN:NT-VERIFY (generated by tools/apply-verification.py — do not edit) -->", "<!-- END:NT-VERIFY -->"

LINKS = ' See <a href="/updates/">live updates</a> and <a href="/sources/">the official sources</a>.'

NOTICES = {
    "kumbh": ("How current is this guide?",
              "This guide was written before the Kumbh Mela&rsquo;s official arrangements were published. Dates, figures, rules, fares, timings and facilities it describes have not been verified against official sources, and some may be out of date or wrong. Where it differs from the dates below, the dates below &mdash; which carry their sources &mdash; take precedence." + LINKS),
    "passes": ("No pass or registration scheme has been announced",
               "We could not locate any official announcement of an e-pass or registration requirement for general visitors. Registration has been reported only for religious organisations and student volunteers. Parts of this guide describe a scheme in expectation, not as announced fact. Be cautious of anyone selling a &ldquo;pass&rdquo; before the Authority announces one, and see <a href=\"/kumbh-mela-2027/#passes\">passes and registration</a> on the Kumbh hub."),
    "helicopter": ("A helicopter service is under planning, not announced",
                   "Press coverage reports government tourism planning for helicopter connections for pilgrims, including helipads. We could not locate an operator, routes, prices, seating details or a booking system. Prices, routes, portals and accessibility claims on this page are not confirmed &mdash; read it as speculation, not a booking guide." + LINKS),
    "transport": ("How current is this guide?",
                  "Routes, journey times, fares and train or bus names in this guide come from our earlier research and have not been verified. The Railways say special trains are planned, but no train numbers, routes or dates have been located, and shuttle-bus arrangements have not been announced in sources we found. Check the operators before you travel: see the <a href=\"/transport/\">transport hub</a>." + LINKS),
    "accommodation": ("How current is this guide?",
                      "Hotel names, rates, availability and booking advice here have not been verified against each business&rsquo;s own information. Prices change, especially around the Kumbh. Check directly with the hotel or the booking site, and see <a href=\"/sources/\">our sources</a>."),
    "international": ("How current is this guide?",
                      "Visa, immigration and registration rules change. Figures and requirements in this guide have not been verified against official Government of India sources. Check the current rules before you travel." + LINKS),
    "place": ("How current is this guide?",
              "Opening hours, fees, facilities and arrangements in this guide have not been verified against the venue&rsquo;s or authority&rsquo;s own information, and can change on festival days. Check before you travel. See <a href=\"/sources/\">our sources</a>."),
    "general": ("How current is this guide?",
                "Seasons, prices and arrangements change. Details in this guide have not been verified against official sources. Check before you travel. See <a href=\"/sources/\">our sources</a>."),
}


def dates_line(facts):
    def d(fid):
        f = facts[fid]
        return render.fmt_date(f["value"], short=True) if f.get("value") else render.esc(f["display"])
    sn = "%s, %s, %s (Nashik) and %s (Trimbakeshwar)" % (d("kumbh.snan.1"), d("kumbh.snan.2"), d("kumbh.snan.3.nashik"), d("kumbh.snan.3.trimbak"))
    status = [facts[x]["status"] for x in ("kumbh.mela.opening", "kumbh.mela.closing", "kumbh.snan.1", "kumbh.snan.2", "kumbh.snan.3.nashik", "kumbh.snan.3.trimbak")]
    st = "verified" if all(x == "verified" for x in status) else "reported"
    return ('<p class="sn-dates"><strong>Dates, from our fact database:</strong> Mela opens %s &middot; Amrit Snan %s &middot; Mela concludes %s. %s '
            '<a href="/kumbh-mela-2027/#dates">Dates and sources</a></p>') % (
        d("kumbh.mela.opening"), sn, d("kumbh.mela.closing"), render.fact_badge(st))


def blocks(path, meta, facts):
    title, text = NOTICES[meta["notice"]]
    extra = dates_line(facts) if meta.get("showDates") else ""
    status = """%s
<div class="status-notice" role="note" data-verification="%s">
  <p class="sn-title">%s</p>
  <p>%s</p>
  %s
</div>
%s""" % (S_BEGIN, render.esc(meta["notice"]), title, text, extra, S_END)
    verify = "%s\n%s\n%s" % (V_BEGIN, render.verify_block(
        path, meta.get("verificationStatus", "not_verified"), meta.get("lastVerified"), meta.get("lastReviewed"), meta.get("sources", []),
        caveat="Details can change. Confirm before travelling.", published_at=meta.get("published")), V_END)
    return status, verify


ART_OPEN = re.compile(r'(<article class="article-body"[^>]*>)')
S_RE = re.compile(r"\n?" + re.escape(S_BEGIN) + r".*?" + re.escape(S_END) + r"\n?", re.S)
V_RE = re.compile(r"\n?" + re.escape(V_BEGIN) + r".*?" + re.escape(V_END) + r"\n?", re.S)


def apply(html, path, meta, facts):
    status, verify = blocks(path, meta, facts)
    html = S_RE.sub("", html)
    html = V_RE.sub("", html)
    html, n = ART_OPEN.subn(lambda m: m.group(1) + "\n" + status + "\n", html, count=1)
    if n != 1:
        raise SystemExit("ERROR: %s has no <article class=\"article-body\">" % path)
    i = html.rindex("</article>")
    html = html[:i] + "\n" + verify + "\n" + html[i:]
    return html


def main():
    check = "--check" in sys.argv
    facts = render.facts_index()
    pages = store.load("pages")["pages"]
    changed = 0
    for path, meta in sorted(pages.items()):
        if meta.get("template") != "article":
            continue
        full = os.path.join(ROOT, path.strip("/"), "index.html")
        if not os.path.isfile(full):
            print("  skip (missing) " + path)
            continue
        before = open(full, encoding="utf-8").read()
        after = apply(before, path, meta, facts)
        if after != before:
            changed += 1
            if not check:
                with open(full, "w", encoding="utf-8") as fh:
                    fh.write(after)
    print("%s %d guide(s)" % ("would update" if check else "updated", changed))


if __name__ == "__main__":
    main()
