#!/usr/bin/env python3
"""
Regenerate the homepage "Latest Guides" cards from posts.json.

posts.json is the single source of truth for the blog (it already powers
/blog/). This script renders the three most recent posts into index.html
between the BEGIN/END markers, so the homepage stays crawlable static HTML
instead of client-rendered, and never drifts out of date by hand.

Reading time is counted from each post's real article text — nothing invented.

Usage:  python3 tools/build-home-guides.py
"""
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "nashiktourism")
ROOT = os.path.normpath(ROOT)
HOME = os.path.join(ROOT, "index.html")
POSTS = os.path.join(ROOT, "posts.json")

BEGIN = "<!-- BEGIN:LATEST-GUIDES (generated by tools/build-home-guides.py — do not edit by hand) -->"
END = "<!-- END:LATEST-GUIDES -->"

WPM = 220  # average adult reading speed for web prose

CAT_CLASS = {
    "Kumbh Mela": "cat-kumbh",
    "Travel Tips": "cat-travel",
    "Hotels": "cat-hotels",
    "Planning": "cat-planning",
    "Nashik Guides": "cat-nashik",
    "Travel Guide": "cat-travel",
    "International Travel": "cat-nashik",
}

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def reading_time(slug):
    """Word-count the post's article body. Returns None if the post isn't on disk."""
    path = os.path.join(ROOT, "blog", slug, "index.html")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        html = fh.read()
    for pattern in (r"<script.*?</script>", r"<style.*?</style>",
                    r"<head.*?</head>", r"<nav.*?</nav>", r"<footer.*?</footer>"):
        html = re.sub(pattern, " ", html, flags=re.S | re.I)
    text = re.sub(r"<[^>]+>", " ", html)
    words = len(re.sub(r"\s+", " ", text).split())
    return max(1, round(words / WPM))


def fmt_date(iso):
    try:
        y, m, d = (int(x) for x in iso.split("-"))
        return "%d %s %d" % (d, MONTHS[m - 1], y), iso
    except (ValueError, IndexError):
        return iso, iso


def cloudinary(url, transform):
    """Insert Cloudinary delivery transformations into an /upload/ URL."""
    if "res.cloudinary.com" in url and "/upload/" in url:
        head, tail = url.split("/upload/", 1)
        if re.match(r"^[a-z]_", tail):  # already transformed
            return url
        return "%s/upload/%s/%s" % (head, transform, tail)
    if "images.unsplash.com" in url:
        sep = "&" if "?" in url else "?"
        return "%s%sauto=format&fit=crop" % (url, sep)
    return url


def build_card(post, featured=False):
    slug = post["slug"]
    title = esc(post["title"].split("|")[0].strip())
    excerpt = esc(post["excerpt"].strip())
    if len(excerpt) > 155:
        excerpt = excerpt[:152].rsplit(" ", 1)[0] + "…"
    category = esc(post.get("category", ""))
    pretty, iso = fmt_date(post.get("date", ""))
    mins = reading_time(slug)
    cat_cls = CAT_CLASS.get(post.get("category", ""), "cat-default")

    ar, width, height = ("16:10", 800, 500) if featured else ("3:2", 560, 373)
    img = cloudinary(post["image"], "f_auto,q_auto,c_fill,g_auto,ar_%s,w_%d" % (ar, width))
    img2x = cloudinary(post["image"], "f_auto,q_auto,c_fill,g_auto,ar_%s,w_%d" % (ar, width * 2))
    sizes = ("(max-width: 768px) 92vw, (max-width: 1024px) 46vw, 40vw" if featured
             else "(max-width: 768px) 92vw, (max-width: 1024px) 46vw, 28vw")

    read_bit = ""
    if mins:
        read_bit = '<span class="bread">%d min read</span>' % mins

    # alt="" is deliberate: the card's own <h3> already names the article, so a
    # descriptive alt here would just be read out twice by a screen reader.
    return """      <a href="/blog/%s/" class="bcard fade-up">
        <div class="bcard-img">
          <img src="%s" srcset="%s %dw, %s %dw" sizes="%s"
               width="%d" height="%d" alt="" loading="lazy" decoding="async" />
        </div>
        <div class="bcard-body">
          <div class="bmeta">
            <span class="bcat %s">%s</span>
            <time datetime="%s">%s</time>%s
          </div>
          <h3>%s</h3>
          <p>%s</p>
          <span class="rlink">Read the guide <span aria-hidden="true">&rarr;</span></span>
        </div>
      </a>""" % (slug, img, img, width, img2x, width * 2, sizes, width, height,
                 cat_cls, category, iso, pretty, read_bit, title, excerpt)


def main():
    with open(POSTS, encoding="utf-8") as fh:
        posts = json.load(fh)

    posts.sort(key=lambda p: p.get("date", ""), reverse=True)
    latest = posts[:3]

    cards = "\n".join(build_card(p, featured=(i == 0)) for i, p in enumerate(latest))
    block = "%s\n%s\n    %s" % (BEGIN, cards, END)

    with open(HOME, encoding="utf-8") as fh:
        html = fh.read()

    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(html):
        sys.exit("ERROR: markers not found in index.html — nothing written.")

    html = pattern.sub(lambda _: block, html, count=1)
    with open(HOME, "w", encoding="utf-8") as fh:
        fh.write(html)

    print("Wrote %d guide cards into index.html:" % len(latest))
    for p in latest:
        mins = reading_time(p["slug"])
        print("  %s  %-14s  %s min" % (p["date"], p.get("category", ""), mins or "?"))


if __name__ == "__main__":
    main()
