#!/usr/bin/env python3
"""
Generate the homepage (index.html): utility first, identity second.

    Header
    Search Nashik                 <- hero: the question, a search box, popular searches
    NASHIK — LIVE band            <- only during the live Kumbh phase (data-driven)
    Nashik Now                    <- weather, latest update, next event — each with a timestamp
    Kumbh 2027                    <- phase-aware: standard / live / reduced
    What are you looking for?     <- eight real questions, each showing how well we can answer it
    Latest updates
    Explore Nashik                <- preserved from the previous homepage
    Plan your trip                <- preserved
    Latest guides                 <- generated from posts.json, as before
    About / Trust                 <- preserved, plus the river story
    Footer

Nothing decorative sits above the answers: the hero is only as tall as its
content, and its photograph is applied by CSS at 720px+ so phones never download
it. Sections that survived from the previous homepage live in
tools/templates/home/ so their copy and markup are unchanged.
"""
import importlib.util
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nt import content, lifecycle, pagekit, render, store  # noqa: E402
from nt.paths import ROOT, SITE  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
TPL = os.path.join(HERE, "templates", "home")
HERO_IMG = ("https://res.cloudinary.com/duhuxaukd/image/upload/f_auto,q_auto,c_fill,g_auto,ar_16:9,w_1600/"
            "v1775450543/rishu-bhosale-LO0KOsgTEA0-unsplash_hqa4n3.jpg")

GUIDES_BEGIN = "<!-- BEGIN:LATEST-GUIDES (generated by tools/build-home-guides.py — do not edit by hand) -->"
GUIDES_END = "<!-- END:LATEST-GUIDES -->"


def tpl(name):
    with open(os.path.join(TPL, name), encoding="utf-8") as fh:
        return fh.read()


def status_line(fid, facts, fallback):
    f = facts.get(fid)
    if not f:
        return fallback
    return {"verified": "Verified " + (render.fmt_date(f.get("verifiedAt"), short=True) if f.get("verifiedAt") else ""),
            "reported": "Reported, not yet confirmed",
            "not_verified": "Not yet verified",
            "disputed": "Sources differ"}[f["status"]]


def intent_tiles(facts):
    tiles = [
        ("Trimbakeshwar timings?", "Hours not yet confirmed. See what we know.", "/discover-nashik/trimbakeshwar/#quick-facts"),
        ("How do I reach Nashik?", "Air, train, bus and road, with official sources.", "/transport/"),
        ("When are the Kumbh dates?", status_line("kumbh.snan.1", facts, "Reported") + ".", "/kumbh-mela-2027/#dates"),
        ("Do I need a Kumbh pass?", "None announced that we can find. " + status_line("kumbh.pass.general", facts, "") + ".", "/kumbh-mela-2027/#passes"),
        ("Kumbh parking and roads?", "No official plan located yet.", "/kumbh-mela-2027/#parking-roads"),
        ("Where should I stay?", "Areas and options, and how to book.", "/blog/where-to-stay-nashik-kumbh-mela/"),
        ("Is it accessible?", "Access status of each place, honestly marked.", "/accessible-nashik/"),
        ("What&rsquo;s on?", "Events, each with its source.", "/events/"),
    ]
    return "".join('<li><a class="intent-tile" href="%s"><span class="it-q">%s</span><span class="it-a">%s</span></a></li>' % (h, q, a) for q, a, h in tiles)


def now_strip(built):
    updates = content.live_updates(limit=1)
    upcoming, _ = content.events()
    nxt = upcoming[0] if upcoming else None
    if updates:
        u = updates[0]
        upd = """<a class="now-card" href="/updates/#u-%s" style="text-decoration:none;">
        <p class="nc-label">Latest update</p><p class="nc-main">%s</p>
        <p class="nc-sub">%s</p><p class="nc-stamp">%s &middot; Source: %s &middot; Last checked %s</p></a>""" % (
            render.esc(u["id"]), render.esc(u["title"]), render.update_badge(render.effective_status(u)),
            "Published " + render.esc(render.fmt_date(u["publishedAt"], short=True)), render.esc(u["sourceName"]), render.esc(render.fmt_date(u["lastCheckedAt"], short=True)))
    else:
        upd = """<div class="now-card"><p class="nc-label">Latest update</p><p class="nc-main">No live updates</p>
        <p class="nc-sub">Nothing is published as live right now.</p><a class="nc-link" href="/updates/">Updates and archive</a></div>"""
    if nxt:
        ev = """<a class="now-card" href="/events/#e-%s" style="text-decoration:none;">
        <p class="nc-label">Next event</p><p class="nc-main">%s</p>
        <p class="nc-sub">%s &middot; %s</p><p class="nc-stamp">%s &middot; Last checked %s</p></a>""" % (
            render.esc(nxt["id"]), render.esc(nxt["title"]), render.esc(render.fmt_date(nxt["date"], weekday=True)), render.esc(nxt["location"]),
            "Verified" if nxt["verificationStatus"] == "verified" else "Reported, not yet confirmed",
            render.esc(render.fmt_date(nxt["lastCheckedAt"], short=True)) if nxt.get("lastCheckedAt") else "not recorded")
    else:
        ev = """<div class="now-card"><p class="nc-label">Next event</p><p class="nc-main">None listed</p>
        <p class="nc-sub">We list an event only with a named source.</p><a class="nc-link" href="/events/">Events</a></div>"""
    wx = """<div class="now-card"><p class="nc-label">Weather in Nashik</p>
        <div data-weather="compact" aria-live="polite"><p class="nc-sub">Loading the weather. Official forecasts: <a class="nc-link" href="https://mausam.imd.gov.in/" rel="noopener noreferrer">IMD</a>.</p></div></div>"""
    return """<section class="sec sec-alt" aria-labelledby="now-h"><div class="inner">
    <h2 class="sec-title" id="now-h">Nashik now</h2>
    <p class="sec-sub">What is happening, with the time each item was last checked.</p>
    <div class="now-grid">%s%s%s</div>
    <p class="link-row"><a class="btn btn-outline" href="/nashik-now/">Open Nashik Now</a></p>
  </div></section>""" % (wx, upd, ev)


def kumbh_block(prof, facts):
    def d(fid, label):
        f = facts[fid]
        return '<li><span class="kc-d">%s</span><span class="kc-l">%s &middot; %s</span></li>' % (
            render.esc(f["display"].replace("Monday ", "").replace("Tuesday ", "").replace("Saturday ", "").replace("Sunday ", "")),
            render.esc(label), render.esc(render.FACT_BADGES[f["status"]][1]))
    top = """<section class="sec" data-phase-id="preparation mela_open peak extended"%s aria-labelledby="k-h"><div class="inner">
    <div class="kumbh-card">
      <p class="kc-kicker">Simhastha Kumbh Mela 2026&ndash;28 &middot; %s</p>
      <h2 id="k-h">Kumbh Mela 2027</h2>
      <p>The Simhastha comes to Nashik and Trimbakeshwar. Dates and arrangements are still being confirmed, so each date here is marked with how sure we are.</p>
      <ul class="kc-dates">%s</ul>
      <p class="kc-caveat">Check with the official authority before travelling. <a class="lb-link" href="/kumbh-mela-2027/#dates">What is confirmed, and what is not</a></p>
      <div class="kc-actions">
        <a class="btn btn-primary" href="/kumbh-mela-2027/">Kumbh hub</a>
        <a class="btn btn-secondary" href="/kumbh-mela-2027/live-updates/">Live updates</a>
        <a class="btn btn-secondary" href="/kumbh-mela-2027/#passes">Passes: what is known</a>
      </div>
    </div></div></section>""" % ("" if prof["id"] in ("preparation", "mela_open", "peak", "extended") else " hidden",
                                  render.esc(prof["label"]),
                                  d("kumbh.mela.opening", "Mela opens") + d("kumbh.snan.1", "1st Amrit Snan") + d("kumbh.snan.2", "2nd Amrit Snan") + d("kumbh.snan.3.nashik", "3rd Amrit Snan (Nashik)"))
    reduced = """<section class="sec sec-stone" data-phase-id="post_kumbh evergreen"%s aria-labelledby="kr-h"><div class="inner">
    <h2 class="sec-title" id="kr-h">Kumbh Mela: guides and history</h2>
    <p class="sec-sub">The Simhastha is part of Nashik&rsquo;s story. Our Kumbh guides and the record of what was announced remain available.</p>
    <p class="link-row"><a class="btn btn-outline" href="/kumbh-mela-2027/">Kumbh hub</a><a class="btn btn-outline" href="/updates/archive/">Update archive</a></p>
  </div></section>""" % ("" if prof["id"] in ("post_kumbh", "evergreen") else " hidden")
    return top, reduced


def latest_updates_block():
    ups = content.live_updates(limit=3)
    lst = ('<div class="update-list">%s</div>' % "".join(render.update_card(u, tag="h3", compact=True) for u in ups)) if ups else \
        '<div class="empty-state"><h3>No live updates right now</h3><p>We publish an update only after an editor checks its source. See the <a href="/updates/archive/">archive</a> or <a href="/sources/">where to check for yourself</a>.</p></div>'
    return """<section class="sec" aria-labelledby="up-h"><div class="inner">
    <h2 class="sec-title" id="up-h">Latest updates</h2>
    <p class="sec-sub">Verified notices, each with its source and when it was last checked.</p>
    %s
    <p class="link-row"><a class="btn btn-outline" href="/updates/">All updates</a><a class="btn btn-outline" href="/updates/feed.xml">Feed</a></p>
  </div></section>""" % lst


def guides_cards():
    spec = importlib.util.spec_from_file_location("bhg", os.path.join(HERE, "build-home-guides.py"))
    bhg = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(bhg)
    posts = json.load(open(os.path.join(ROOT, "posts.json"), encoding="utf-8"))
    posts.sort(key=lambda p: p.get("date", ""), reverse=True)
    return "\n".join(bhg.build_card(p, featured=(i == 0)) for i, p in enumerate(posts[:3]))


HOME_CSS_EXTRA = """    .home-hero { background-color: var(--dark); }
    @media (min-width: 720px) { .home-hero { background-image: linear-gradient(to bottom, rgba(15,10,30,0.74) 0%%, rgba(15,10,30,0.82) 55%%, rgba(15,10,30,0.96) 100%%), url('%s'); background-size: cover; background-position: center; } .home-hero::after { display: none; } }
    .section-eyebrow { font-family: var(--font-display); font-size: 0.72rem; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: var(--saffron-deep); margin-bottom: 0.6rem; }
    .section-title { font-family: var(--font-display); font-size: clamp(1.5rem, 5.4vw, 2.6rem); font-weight: 800; color: var(--ink); line-height: 1.15; letter-spacing: -0.02em; margin-bottom: 0.7rem; }
    .section-sub { font-size: 1rem; color: var(--muted); max-width: 52ch; line-height: 1.7; margin-bottom: 2rem; }
    .trust-sec { background: var(--light); }
    .trust-more { margin-top: var(--s-6); }
    .trust-more a { color: var(--primary); font-weight: 700; text-decoration: underline; text-underline-offset: 2px; }"""


def main():
    facts = render.facts_index()
    prof = lifecycle.profile()
    built = store.now()

    k_top, k_reduced = kumbh_block(prof, facts)
    hero = """<section class="home-hero" aria-labelledby="home-h1">
  <div class="hh-inner">
    <p class="hh-eyebrow">Independent &middot; verified &middot; current</p>
    <h1 id="home-h1">What you need to know about <em>Nashik</em>, right now.</h1>
    <p class="hh-sub">Temples, ghats, vineyards and the Simhastha Kumbh Mela &mdash; every fact with its source and the date we last checked it.</p>
    <form class="hh-form" role="search" action="/search/" method="get">
      <label class="hh-label" for="hh-q">What are you looking for in Nashik?</label>
      <div class="hh-search">
        <input id="hh-q" name="q" type="search" placeholder="e.g. Trimbakeshwar timing" autocomplete="off" autocapitalize="off" spellcheck="false" enterkeyhint="search" />
        <button type="submit" aria-label="Search"><svg class="ico" width="20" height="20" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M10.5 3a7.5 7.5 0 1 0 4.7 13.3l4.5 4.5 1.4-1.4-4.5-4.5A7.5 7.5 0 0 0 10.5 3Zm0 2a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11Z"/></svg><span class="hh-btn-label">Search</span></button>
      </div>
    </form>
    <ul class="hh-try" aria-label="Popular searches">
      <li><a href="/search/?q=Trimbakeshwar+timing">Trimbakeshwar timing</a></li>
      <li><a href="/search/?q=Kumbh+parking">Kumbh parking</a></li>
      <li><a href="/search/?q=Nashik+airport">Nashik airport</a></li>
      <li><a href="/search/?q=Kumbh+2027+dates">Kumbh 2027 dates</a></li>
    </ul>
  </div>
</section>"""
    kb = importlib.util.spec_from_file_location("bk", os.path.join(HERE, "build-kumbh.py"))
    bk = importlib.util.module_from_spec(kb)
    kb.loader.exec_module(bk)
    live_band = bk.live_band(prof)

    intent = """<section class="sec" aria-labelledby="intent-h"><div class="inner">
    <h2 class="sec-title" id="intent-h">What are you looking for?</h2>
    <p class="sec-sub">The questions people ask first &mdash; each tile says how well we can answer it today.</p>
    <ul class="intent-grid">%s</ul>
  </div></section>""" % intent_tiles(facts)

    guides_hdr = """<section class="blog-sec" aria-labelledby="guides-h">
  <div class="blog-hdr">
    <div>
      <p class="section-eyebrow">Travel Guides</p>
      <h2 class="section-title" id="guides-h" style="margin-bottom:0.2rem;">Latest guides &amp; tips</h2>
      <p class="section-sub">Longer guides to the city. Each shows how current it is.</p>
    </div>
    <a href="/blog/" class="view-all">View all guides <span aria-hidden="true">&rarr;</span></a>
  </div>
  <div class="blog-grid">
    %s
%s
    %s
  </div>
</section>
""" % (GUIDES_BEGIN, guides_cards(), GUIDES_END)

    trust = tpl("trust.html")
    trust = trust.replace("""      <p>Timings, fees and festival arrangements change, and Kumbh Mela plans in particular are still being finalised. Please confirm details with official sources close to your travel date.</p>
    </div>""", """      <p>Timings, fees and festival arrangements change, and Kumbh Mela plans in particular are still being finalised. Please confirm details with official sources close to your travel date.</p>
    </div>""")
    trust = trust.replace("</section>", """  <p class="trust-more"><a href="/editorial-policy/">How we verify what we publish</a> &middot; <a href="/sources/">Our sources</a> &middot; <a href="/disclaimer/">Disclaimer</a></p>
</section>""", 1)

    body = "\n".join([
        live_band, hero, now_strip(built), k_top, intent, latest_updates_block(),
        tpl("explore.html"), tpl("plan.html"), tpl("dur.html"), guides_hdr, k_reduced,
        tpl("about.html"), tpl("split.html"), trust, tpl("hotel.html"),
        '<script type="application/json" id="nt-phases">%s</script>' % json.dumps(lifecycle.client_payload()).replace("</", "<\\/"),
        '<script src="/now.js" defer></script>'])

    css = HOME_CSS_EXTRA % HERO_IMG + "\n" + open(os.path.join(TPL, "home.css"), encoding="utf-8").read()
    ld = [
        {"@type": "Organization", "@id": SITE + "/#organization", "name": "NashikTourism.com", "url": SITE + "/",
         "logo": {"@type": "ImageObject", "url": SITE + "/logo-purple.png", "width": 512, "height": 512},
         "description": "An independent travel and information guide to Nashik, Maharashtra. Not affiliated with any government body or official tourism authority."},
        {"@type": "WebSite", "@id": SITE + "/#website", "url": SITE + "/", "name": "Nashik Tourism",
         "description": "An independent, continuously verified guide to Nashik, Maharashtra: temples, vineyards, the Simhastha Kumbh Mela, transport, accessibility and events.",
         "publisher": {"@id": SITE + "/#organization"}, "inLanguage": "en-IN",
         "potentialAction": {"@type": "SearchAction", "target": {"@type": "EntryPoint", "urlTemplate": SITE + "/search/?q={search_term_string}"}, "query-input": "required name=search_term_string"}},
        {"@type": "TouristDestination", "@id": SITE + "/#destination", "name": "Nashik",
         "description": "A city on the Godavari river in Maharashtra, India, known for its temples and river ghats, for hosting the Simhastha Kumbh Mela, for the vineyards in the surrounding hills, and for the Western Ghats hill country nearby.",
         "url": SITE + "/", "image": pagekit.OG_DEFAULT,
         "address": {"@type": "PostalAddress", "addressLocality": "Nashik", "addressRegion": "Maharashtra", "addressCountry": "IN"},
         "touristType": ["Religious tourism", "Wine tourism", "Heritage tourism", "Nature tourism"]}]
    html = pagekit.render(
        "/", "Nashik Tourism: what you need to know about Nashik right now",
        "An independent, verified guide to Nashik: search destinations, see the latest updates, plan a trip and follow Simhastha Kumbh Mela 2027, with a source and a last-checked date on every fact.",
        body, css=css, jsonld=ld, raw_title=True, page_type="WebPage",
        extra_head='<link rel="alternate" type="application/atom+xml" title="NashikTourism.com verified updates" href="/updates/feed.xml" />')
    # The home page's WebPage node is described by the TouristDestination.
    pagekit.write("/", html)
    print("home built (phase: %s)" % prof["id"])


if __name__ == "__main__":
    main()
